logger:
  name: run
  level: info
  caller: true
  formatter:
    type: text
  hooks:
    - type: file
      level: info
      file: ${ProjectDir}/examples/log/run.log
      size: 1024
      backup: 3
      days: 7
      compress: false
    - type: stdout
      level:
        - info
        - warn
        - debug
        - trace
    - type: stderr
      level:
        - error
        - panic
        - fatal
    - type: telegram
      level: info
      token: 5515503471:AAHilqY6UuixG22Jayl94re01ly4CIL0dTM
      chat_id: -1001535194188