logger:
  name: run
  level: info
  formatter:
    type: text
    time_format: 2006/01/02 15:04:05.0000000
  hooks:
    - type: file
      header: true
      level: info
      file: ${ProjectDir}/examples/logger/log/run.log
      size: 1024
      backup: 3
      days: 7
      compress: false
    - type: stdout
      header: true
      level:
        - info
        - warn
        - debug
        - trace
    - type: stderr
      header: true
      level:
        - error
        - panic
        - fatal
    - type: telegram
      header: false
      level: panic
      token: 5515503471:AAHilqY6UuixG22Jayl94re01ly4CIL0dTM
      chat_id: -1001535194188